### ISSUE TITLE
How can I find pkcs11.so file

### ISSUE THREAD

**Issue by pramodshinde** [larskanis/pkcs11#8]
I have provisioned AWS Linux machine with CloudHSM client and ./cloudhsm-client-pkcs11-latest.el6.x86_64.rpm installed on It. I could successfully install this gem. 

I need to know where to find `/path/to/pkcs11.so` file, So I can launch a session using this gem. 

Or Am I missing some libraries?

**Comment by larskanis** [comment]
Have a look into `/opt/cloudhsm/lib` according to https://docs.aws.amazon.com/cloudhsm/latest/userguide/pkcs11-library-install.html#install-pkcs11-library

**Comment by pramodshinde** [comment]
Yes, I found it at `/opt/cloudhsm/lib/libcloudhsm_pkcs11.so` on ec2
Thanks.
